import { StyleSheet } from "react-native";
import { DarkTheme } from "../../theme/DarkTheme";
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        padding: 16,
        paddingTop: 26,
    },
    center: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#000",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
    },
    avatar: {
        width: 100,
        height: 100,
        borderRadius: 55,
        marginRight: 20,
    },
    statsContainer: {
        flexDirection: "row",
        flex: 1,
        justifyContent: "space-around",
    },
    statBox: {
        alignItems: "center",
    },
    statNumber: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
    },
    statLabel: {
        color: "#aaa",
        fontSize: 13,
    },
    username: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
        marginTop: 15,
    },
    usernameRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    editIcon: {
        marginLeft: 7,
        marginTop: 15,
    },
    bio: {
        color: "#ccc",
        marginTop: 8,
        maxHeight: 70,
    },
    buttonRow: {
        flexDirection: "row",
        marginTop: 20,
    },
    editButton: {
        flex: 1,
        backgroundColor: "#222",
        padding: 10,
        borderRadius: 8,
        marginRight: 10,
        alignItems: "center",
    },
    editText: {
        color: "#fff",
    },
    logoutButton: {
        flex: 1,
        backgroundColor: DarkTheme.PRIMARY_BUTTON,
        padding: 10,
        borderRadius: 8,
        alignItems: "center",
    },
    logoutText: {
        color: "#000",
        fontWeight: "bold",
    },
    modalContainer: {
        backgroundColor: DarkTheme.PRIMARY_BACKGROUND,
        flex: 1,
        padding: 20,
        justifyContent: "center",
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 20,
        color: "#fff",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ccc",
        padding: 10,
        borderRadius: 8,
        height: 100,
        lineHeight: 20,
        fontSize: 20,
        textAlignVertical: "top",
        color: "#fff",
    },
    inputUsername: {
        borderWidth: 1,
        borderColor: "#ccc",
        padding: 10,
        borderRadius: 8,
        height: 40,
        lineHeight: 20,
        fontSize: 20,
        textAlignVertical: "top",
        color: "#fff",
    },
    saveButton: {
        marginTop: 20,
        backgroundColor: DarkTheme.PRIMARY_BUTTON,
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    saveText: {
        fontWeight: "bold",
    },
    usernameInput: {
        borderWidth: 1,
        borderColor: "#fff",
        borderRadius: 8,
        padding: 10,
        color: "#fff",
    },
    usernameInputContainer: {
        marginTop: 20,
    },
    savesButton: {
        marginTop: 20,
        backgroundColor: DarkTheme.PRIMARY_BUTTON,
        padding: 12,
        borderRadius: 8,
        width: "40%",
        alignItems: "center",
    },
    savesText: {
        color: "#000",
    },
    cancelsButton: {
        marginTop: 20,
        marginRight: "5%",
        backgroundColor: "#222",
        padding: 12,
        borderRadius: 8,
        width: "40%",
        alignItems: "center",
    },
    cancelsText: {
        color: "#fff",
    },
    buttonsRow: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalBox: {
        width: "88%",
        backgroundColor: "#111",
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: "#222",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 10,
    },
});
